### ISSUE TITLE
Problem after the v5 app update 

### ISSUE THREAD

**Issue by perzon81** [hankolsen/com.securemeters.horstmann#1]
Hi,

Thanks for the v5 update! I however encountered some issues after that. I have added my SRT 321, but I am not able to get any temperature values from the device or change the temperature from the app. When I try to change the temperature from the app I get an "invalid device" error, see add screenshoot. I have tried to exclude and include it several times, the result always looks successful in both the app and on the device). I have also tried to restart my Homey a couple of times without any visible impact. 

Diagnostic code :
ae367b62-f510-41d8-acd8-e9288de2d897

![Screenshot_20210301-204727_Homey](https://user-images.githubusercontent.com/73080817/109551908-7125fa80-7ad1-11eb-908f-231409d4b91f.jpg)

**Comment by hankolsen** [comment]
Thank you!
I'll investigate
