### ISSUE TITLE
SRT321 dont want to work after 5.0

### ISSUE THREAD

**Issue by pln8421** [hankolsen/com.securemeters.horstmann#15]
Hi. I have two SRT321. Will not work after upgrading os to 5.0. 
I now have latest versions but still no action on my two devices. Do I need to remove them and include them again?

d9655ae6-9be0-436f-96d6-891b7d5edb19

/Per

**Comment by hankolsen** [comment]
Hi!
Thank you for reporting this.
I can confirm you problem, so I'll investigate.
Please hold on

**Comment by hankolsen** [comment]
Hi again!

I just tried to remove and re-include mine and it started working again. It’s strange because you shouldn’t have to do that.
Please try to remove and re-include and let me know if that solves your issue or not!

/Hank

**Comment by hankolsen** [comment]
Any luck @pln8421 ?

**Comment by pln8421** [comment]
Hello
Thanks for asking 😃
Yes, I deleted both devices from app and added again. Not I can see the device and change set value.
I added the heaters I want to be able to turn of and on, in advance settings but this does not work.


Best regards Per

12 apr. 2021 kl. 07:33 skrev hankolsen ***@***.***>:

﻿

Any luck @pln8421<https://github.com/pln8421> ?

**Comment by hankolsen** [comment]
And you have the heaters added to Group 3 of the SRT321?

**Comment by pln8421** [comment]
Hello
Yes:
[cid:0225684D-587E-4F1B-AEE5-EEE46B4BA8A2-L0-001][cid:2118ED3C-5ECD-453E-BEFC-84126E8DC72D-L0-001]


Hälsningar Per

12 apr. 2021 kl. 16:10 skrev hankolsen ***@***.***>:

﻿

And you have the heaters added to Group 3 of the SRT321?

**Comment by pln8421** [comment]
Hello
I did the same with SRT321 no 2 and it behave the same as no 1.
I can add it, I see it. I can adjust setting but connection plug does not work. No reaction at all.
Device is added in group3.
V0.5.8 and v5.0.4 in Homey

Best Regards Per

12 apr. 2021 kl. 16:10 skrev hankolsen ***@***.***>:

﻿

And you have the heaters added to Group 3 of the SRT321?

**Comment by hankolsen** [comment]
Om du ändrar temperaturen med hjulet på själva SRT321:an. uppdateras de anslutna värmarna då?

**Comment by pln8421** [comment]
Hej
Nej. Händer inget med reläerna.
Har för mig att innan 5.0 så låg devicens ID på Grupp 1 eller 2.
Då fungerade det.


Hälsningar Per

13 apr. 2021 kl. 14:52 skrev hankolsen ***@***.***>:

﻿

Om du ändrar temperaturen med hjulet på själva SRT321:an. uppdateras de anslutna värmarna då?

**Comment by hankolsen** [comment]
Hmm, skumt. Jag har själv en SRT321 och mina uttag jag styr är på grupp 3.
Skulle du kunna göra en diagnosrapport nu igen, när den har kört en stund?

**Comment by pln8421** [comment]
Hej
Här kommer länken till diagnostikrapporten:

631322be-926a-4d4a-bf07-c7f6c1de5624


Hälsningar Per

13 apr. 2021 kl. 16:26 skrev hankolsen ***@***.***>:

﻿

Hmm, skumt. Jag har själv en SRT321 och mina uttag jag styr är på grupp 3.
Skulle du kunna göra en diagnosrapport nu igen, när den har kört en stund?

**Comment by pln8421** [comment]
Hej igen
Köpte 2 nya SRT321 och de går inte includera i Homey. 
nu har jag 2 äldre och 2 nya. 
Homey är uppdaterad. 

https://user-images.githubusercontent.com/40936900/147818241-465dbef1-eb77-4a14-b545-33a53d8e58e8.MOV

/Per

**Comment by hankolsen** [comment]
Hej Per!
Jag är hemskt ledsen, men jag vet inte vad som kan vara fel.
Mitt bästa förslag är att kontakta Homey och be deras support om hjälp.
