### ISSUE TITLE
Can not add SES303

### ISSUE THREAD

**Issue by arvid-r** [hankolsen/com.securemeters.horstmann#16]
My SES303 used to work, but stopped doing so some time ago. I removed the device and tried to add it again but that fails with the following error:
`status.missing_multiChannelNodeId_1_on_node`
Let me know if I can do something to help sort out this issue!

**Comment by hankolsen** [comment]
Are using the latest version? This issue should have been resolved

**Comment by arvid-r** [comment]
I'll check. Stand by ...

**Comment by arvid-r** [comment]
I'm using v0.5.4

**Comment by hankolsen** [comment]
Ah, sorry, I mixed up the devices. It was ssr303 that was resolved in the latest release.

Let me look into this tomorrow

**Comment by arvid-r** [comment]
Thanks! And please let me know if you need any further information.

**Comment by hankolsen** [comment]
@arvid-r Please try the latest test version (v0.5.5) here: https://homey.app/a/com.horstmann/test/

**Comment by arvid-r** [comment]
Thanks for the update!
I get a new error now:
`status.missing_multiChannelNodeId_2_on_node`

**Comment by hankolsen** [comment]
@Rocodamelshe are you still able to use your ses303?

**Comment by hankolsen** [comment]
@arvid-r , I made another update to v0.5.6, available as test now.
I'm sorry, since I don't have access to anything but the SRT321 I have not been able to verify (or debug) any other devices, so it is a bit of trial and error.

**Comment by Rocodamelshe** [comment]
The SES303 is working like it should. The attached multichannel device is not updating any temperature for now. Gonna try a re-add and let u know.

**Comment by arvid-r** [comment]
Still:
`status.missing_multiChannelNodeId_2_on_node`

**Comment by hankolsen** [comment]
Hmm, this is odd. I’ll try some more...

**Comment by Rocodamelshe** [comment]
Removed the SES303 on version 0.5.6 and added it again. Then i get this:

![chrome_2021-04-11_20-24-25](https://user-images.githubusercontent.com/19249884/114316574-73ce3380-9b04-11eb-9aac-c13f34543dee.png)

**Comment by hankolsen** [comment]
Ok, so at least there is some consistency between your setups.

I found this in the SES302/303 manual:

"Up to a maximum of five end points supported. The number of end points on the product is detected based on the number of external sensors connected to the product at the time of Inclusion.  **If external sensor not connected this command class is not supported.**  Note: external digital sensors must have correct hardware address otherwise it will not work."

I'm guessing @arvid-r  doesn't have any external sensors connected and @Rocodamelshe has one connected?

**Comment by Rocodamelshe** [comment]
Correct for my part yes.

**Comment by hankolsen** [comment]
I guess I need to figure out how the configuration works "If external sensor not connected this command class is not supported.", and dynamically add the command class.

**Comment by arvid-r** [comment]
I have no sensor connected.

**Comment by hankolsen** [comment]
Let's try v0.5.7 in test now :)

**Comment by Rocodamelshe** [comment]
Devices are added! Will let u know tonight if the sensor updates it’s values.

![Uploading D64DE6FC-3308-4EDF-B8EF-24F95C9CA9DF.jpeg…]()

**Comment by arvid-r** [comment]
v0.5.7 works with my setup! Well done

**Comment by Rocodamelshe** [comment]
Works like a charm, cheers m8!

**Comment by hankolsen** [comment]
You are trying to get me drunk @Rocodamelshe!

Thanks!
