### ISSUE TITLE
Help with adding SSR-302 Dual Channel boiler controller to the app

### ISSUE THREAD

**Issue by jmdraper** [hankolsen/com.securemeters.horstmann#19]
Hi

I am brand new to Homey and just getting everything set up. I have been a long-time (~15 years) home Automator with other platforms so I have a large fleet of z wave devices I have been migrating. One of these is an SSR-302 dual channel boiler controller which controls hot water as well as heating. I guess it must be pretty similar to the SSR-303 which I see is already supported, though obviously with an extra channel.  The heating channel is paired with an SRT 321 which I know is supported, but I would need also support for the hot water channel. 

As I say I am new to Homey and although I’ve dabbled with JavaScript before and familiar with Z Wave command classes and associations and so on, I’m not yet confident to add this myself. I wonder if either you could help guide me to add support for this myself and contribute it or If you could add support with me testing and providing any diagnostics etc to get it working? Definitely happy to buy you more than one coffee if you can help me get this added!

Thanks,
Jon

**Comment by hankolsen** [comment]
Hi Jon!
I'll try to take a look later tonight!

**Comment by hankolsen** [comment]
@jmdraper Please try the test version, available at https://homey.app/a/com.horstmann/test/

**Comment by jmdraper** [comment]
That’s awesome! Thank you so much. I will have a go tonight and let you know how I get on.

**Comment by jmdraper** [comment]
OK so I installed the test version and managed to successfully pair the device. The device shows up as a single channel device with on/off switch and that controls zone 1 which is the heating

**Comment by hankolsen** [comment]
Ok, that sounds like a good start. I’ll have to dig into the device specifications to figure out how it works with two channels.

**Comment by jmdraper** [comment]
Yes indeed, so far so good. The colours of the LEDs on the device during pairing didn’t quite match the instructions but I guess we can worry about that later! Thank you again for your help here

**Comment by hankolsen** [comment]
@jmdraper I found the pairing instructions in the [manual](https://products.z-wavealliance.org/ProductManual/File?folder=&filename=MarketCertificationFiles/1619/SSR%20302%20User%20Manual.pdf), but it seems to be two different pairing "modes".
Could you please confirm what the pairing process looked like for you?

**Comment by jmdraper** [comment]
Yes - when I held both white buttons I got a flashing amber instead of green as per the instructions. No matter how long I held it did not change from this, so I let go. At this point the '1' turned to a green tick on the Homey pairing screen. I repeated and the same happened again and the '2' turned to a green tick and the device appeared to be successfully paired and I could turn zone 1 on and off from Homey.

**Comment by jmdraper** [comment]
Actually I just re-did the process to triple check. I removed the device first using exclusion mode on Homey and following instructions in the manual which worked exactly as described.

Then when I included again:
* Press and hold two white buttons -> flashing red (not amber as I had remembered) and while I was still holding the two white buttons the '1' on Homey turned to a green tick
* Let go of two white buttons
* Press and hold two white buttons again -> flashing red and while still holding the buttons, '2' turned into a green tick
* Light on SSR302 flashed green a few times
* Light on SSR302 when solid amber and device showed as paired on Homey

**Comment by hankolsen** [comment]
@jmdraper 
I've made v0.6.3 available as a test version.
I've updated the pairing instructions, and tried to add support for the second channel. Unfortunately, I don't own any SSR302, so you'll be my testpilot :)

**Comment by jmdraper** [comment]
Excellent. Thank you once again. Very happy to be your test pilot. I will give it a go today and let you know how I get on.

**Comment by jmdraper** [comment]
Ok I gave it a try. It's still pairing ok in the same way as before. But now at the very end of the pairing process it comes up with a message saying no compatible device has been found so it's been added as a basic z wave device (which it then does). A single basic z wave device then shows up in the devices list. 

I removed the device and re paired it twice (to check for consistency) and had the same results both times.

**Comment by hankolsen** [comment]
Ah, sorry, my bad!
I've published a new test version that hopefully fixes that issue!

**Comment by jmdraper** [comment]
Great stuff, will give that another go later on today and report back

**Comment by jmdraper** [comment]
Some great progress here. Re-paired device with the new version. Device shows up as a single item in the devices list. On tap-and-holding the device to get to its screen, it shows a large power button which controls zone 1 (heating). There is now a little 'menu' near the top of the screen which says 'Turned on' (see image below). Tapping on this menu shows two options which are currently listed as 'Turned on' and 'Turned on'. Picking the other 'Turned on' option goes to a screen which also has a large power button on it (I was able to see the difference as thankfully I had turned the heating zone on, and could see this second screen had the power button showing as off). This power button successfully controls zone 2 (hot water). Excellent!

So clearly the menu labelling needs tweaking and the 'Then' flow cards only have 'Turn on', 'Turn off' and 'Toggle' actions right now and these control zone 1 (heating). But we have control of both zones working now!

**Comment by jmdraper** [comment]
![IMG_5404](https://user-images.githubusercontent.com/20240325/123224932-268a1d00-d4ca-11eb-99be-4d92287ab5d5.PNG)
![IMG_5405](https://user-images.githubusercontent.com/20240325/123224944-28ec7700-d4ca-11eb-9b3b-dead6b0254b1.PNG)

**Comment by hankolsen** [comment]
Great news!
I don't know how to change the labels, I will need to investigate that further.
I also haven't done any flow card configuration at all, so that will also require some digging.
But I'm glad we are on the right track!

**Comment by jmdraper** [comment]
I don't know if this is helpful or not, but yesterday I added a dual relay from Fibaro (FGD 222 / 'Double Relay Switch') to my Homey and when it paired, it appeared as two separate devices in the devices list rather than a single device with that little menu. Not sure if you're able to see the code they used and whether that would be helpful?

**Comment by hankolsen** [comment]
I can't seem to find any FGD-222, could it be FGS-222?
https://github.com/athombv/com.fibaro-example/tree/771862b4c5c235613a8166c5be71a44759178a3d/drivers/FGS-222

**Comment by jmdraper** [comment]
Ah yes my bad. That's the one.

**Comment by hankolsen** [comment]
Thanks!
I basically took the code from there and released a new test version, please give it a try!

**Comment by jmdraper** [comment]
Excellent. I'm on it!

**Comment by jmdraper** [comment]
Bingo! That's done it. Two devices, one controlling heating and the other hot water. Awesome work!

![image](https://user-images.githubusercontent.com/20240325/123257316-e9ce1e00-d4e9-11eb-9008-73dcaf1924b0.png)

**Comment by hankolsen** [comment]
Nice!
The icon was a quick-and-dirty hack, but I hope it looks somewhat like the actual device.

So, what about the flow cards, is there anything the should be implemented there?

**Comment by jmdraper** [comment]
Icon looks great. I guess that's the beauty of this approach - no further work needed on the flow cards since I can use existing on, off and toggle cards separately with each device and that gives me everything I need. I think we're there! Thanks again for your work. I will definitely buy you some coffee!

**Comment by hankolsen** [comment]
Thank you!
I learned some new stuff so it was all good!

I've submitted the latest version for review, usually it gets approved within a day or two.

**Comment by hankolsen** [comment]
Fixed in #20
