### ISSUE TITLE
Enhancement: SES 303 multi channel node: SES 002 default node names 

### ISSUE THREAD

**Issue by theSequencer82** [hankolsen/com.securemeters.horstmann#25]
Hi @hankolsen 

Thank you very much for the smart secure app and for supporting the SES 303 device including the SES 002 external temperature sensor nodes. I'am using Homey Pro since approximately two weeks and from the beginning my "Secure Meters" do work like a charm :)

The only issue regarding usability occurs when trying to distinguish between SES 002 sensor nodes
- within the device detail view (see 1st screenshot below) or
- when trying to find the correct flow trigger card as shown in the 2nd screenshot below.

It seems that the former node specific names have been removed with c785124606ebd5abb461391ce4adf1f43d4d0f8a . So, all temperature nodes are currently named as "Temperature".
Would it be possible to get some default names/titles back such as "Temperature EXT 1, 2, 3, 4" or so?

Thank you very much for your effort 🥇

Happy new year 2022!
Regards,
Claudio

![image](https://user-images.githubusercontent.com/34631732/147988913-af5947af-2458-4c09-bb57-d992569e0bcd.png)

![image](https://user-images.githubusercontent.com/34631732/147988820-dceef110-f148-4c8f-a70a-d282cd4ca048.png)

**Comment by hankolsen** [comment]
Thank you for your suggestion @theSequencer82 !
I'll take a look!

**Comment by hankolsen** [comment]
@theSequencer82 could you please try to install the test version (https://homey.app/a/com.horstmann/test/) 0.7.0 and see if it solves your problem

**Comment by theSequencer82** [comment]
THX @hankolsen
I installed v 0.7.0 and restarted the Homey, but the names of the temperature sensor nodes remain the same.
Do I have to uninstall the app first before installing V 0.7.0?
Or do I have to reinclude the devices to get the capabilitiesObj updated?
[Homey-App-com-horstmann.txt](https://github.com/hankolsen/com.securemeters.horstmann/files/7810422/Homey-App-com-horstmann.txt)
[Homey-Device-SES303.txt](https://github.com/hankolsen/com.securemeters.horstmann/files/7810423/Homey-Device-SES303.txt)

**Comment by hankolsen** [comment]
You don't have to uninstall the app, however, I would like to see if anything changes by re-including the devices.

I am also not sure how and those names are populated so this is a matter of trial and error :)

**Comment by hankolsen** [comment]
@theSequencer82 please try the new test version v0.7.1

**Comment by theSequencer82** [comment]
Hi @hankolsen

Great, it works. Node specific titles now are shown :)
Installing V0.7.1 already led to the update of the titles. So there was no need to re-include the devices first.
Nevertheless I did re-include one of my Secure meters just to confirm if inclusion still works on V0.7.1 

Thank you very much for your effort!
Best Regards,
Claudio

![image](https://user-images.githubusercontent.com/34631732/148276804-9ef15bbd-e7d0-4b61-8508-467825f29b70.png)
![image](https://user-images.githubusercontent.com/34631732/148276929-b1e9e560-add7-4337-8c6c-fea7eb83280d.png)
(Btw.: The android app shows titles with capitol letters.)

**Comment by hankolsen** [comment]
@all-contributors please add @theSequencer82  for idea
