### ISSUE TITLE
Secure SSR302

### ISSUE THREAD

**Issue by SPAeotec** [hankolsen/com.securemeters.horstmann#29]
I Get a new SSR 302.

It is added after inclusion as an unknown device.

I suspect that the ID has changed.

The ID of my device is 89.3.6

Can you please check this and add it if necessary.

**Comment by hankolsen** [comment]
Hi @SPAeotec !
Thank you for reporting this!
Please try v0.8.0 that is in available as a test version here: https://homey.app/sv-se/app/com.horstmann/Secure-Meters/test/

**Comment by hankolsen** [comment]
@all-contributors please add @SPAeotec for bug
