### ISSUE TITLE
Scs317 support

### ISSUE THREAD

**Issue by ViaraiX** [hankolsen/com.securemeters.horstmann#33]
Hi, I’m new and not really sure if this is the right area to request support for the scs317 device. It’s a 7-day timer, but just temp control / set point and a temp readout would be great.

Happy to try and help, if possible… it just gets recognised as a no app general zwave device in homey: presumably because the ID isn’t recorded?

please help ☺️

**Comment by hankolsen** [comment]
I'll take a look!

**Comment by hankolsen** [comment]
@ViaraiX, please try the test version v0.9.1 available here: https://homey.app/sv-se/app/com.horstmann/Secure-Meters/test/

**Comment by ViaraiX** [comment]
Hi @hankolsen, great job. Works well. Haven’t fully tested the set point changes, but so far everything works perfectly.

One change you might wish to make, is with the wording for inclusion.

Everything is correct, but you have to set the unit to learn, ensure it says “network data received”, and set it to learn for a second time in order to be successful. Not sure if that’s just a quirk with the SCS317, but useful to know. I tried a few included and excludes to see if that was atypical, but two efforts of “learn mode” were required.

I tried a “learn” and a “send nif” instead, but this doesn’t include.

Hope that’s useful.

Also, thanks for being so quick and doing a great job. ☺️🤘🏻

**Comment by hankolsen** [comment]
@ViaraiX I update the learn instructions in v0.9.2

**Comment by ViaraiX** [comment]
Top work, thanks! 🤘🏻
________________________________
