### ISSUE TITLE
SCS317

### ISSUE THREAD

**Issue by Panther21** [hankolsen/com.securemeters.horstmann#35]
Unfortunately I can't add scs317. I do it according to the description, but at the end homey says something is wrong. i'll try later.
Please help!

**Comment by ViaraiX** [comment]
Hi,

Is this a new 317? I’d go to zwave settings and reset the zwave network on your SCS317. Then “learn” on scs317. It should say network information received. Then immediately go to “learn” again.

I would also move the scs317 or the homey so they are within one metre distance of each other and no walls. This is a homey shortcoming. Let me know how you get on and any specific errors /screenshot/video etc.

**Comment by Panther21** [comment]
Hi!

This is not new.
The first part of learning is ok (network data recevied).
Homey also indicates the second step in green (ok), but after much thought
it says:Something went wrong while adding the device.
Please try again later.
And scs317 says that for the second time: learn mode failed.
I'm clueless.
Thanks if you can help

Üdvözlettel:
Szalai László
+36 30 3394 530
An Armed man Is a Citizen
An Unarmed Man Is a Subject


ViaraiX ***@***.***> ezt írta (időpont: 2022. aug. 24., Sze,
13:58):

**Comment by Panther21** [comment]
off course reset I it

**Comment by Panther21** [comment]
I tried everything you wrote, but unfortunately it doesn't work

**Comment by ViaraiX** [comment]
You could also check what firmware of homey you’re running? It should be 8.0.4.

And try again, making sure they’re both within a metre or about 3 feet of each other.

I’ve deleted mine and re-included it to see if there’s a change, but it worked fine as per instructions.
________________________________

**Comment by Panther21** [comment]
Hi!
Unfortunately, he doesn't accept it either way.
I tried the new 8.05 but no.

Üdvözlettel:
Szalai László
+36 30 3394 530
An Armed man Is a Citizen
An Unarmed Man Is a Subject


ViaraiX ***@***.***> ezt írta (időpont: 2022. aug. 25., Cs,
9:35):
