### ISSUE TITLE
make it work like an actuall thermostat?

### ISSUE THREAD

**Issue by cdx873v** [hankolsen/com.securemeters.horstmann#40]
Hi!

is there a tutorial or something to make it work? all i've managed it to do, is switch on/off at every change in temperature setting. and i dont even know if it will turn on/off when the temperature is reached.

i just want it to be a thermostat and controll my aeon labs micro switch. theres gotta be something i'm missing here?!

**Comment by cdx873v** [comment]
forgot the model. its a SRT321

**Comment by hankolsen** [comment]
The way I have set mine up is via Groups in Advanced Settings in the SRT321 in Homey.

First I get the unit ID of each device that I want to be controlled:

    Open the Homey app
    Click the unit that you want to be controlled
    Click the cog wheel in the top right corner
    Click Advanced Settings
    Scroll down to Unit information for Z-Wave
    Take note of the Unit Id

Then I add those Unit Id's to the SRT321 under Group 3

    Open the Homey app
    Click the SRT321 icon
    Click the cog wheel in the top right corner
    Click Advanced Settings
    Under Group 3, you can add a comma separated list of the unit id's of the units that you want to be controlled. Example: 37,38

Hope that helps!

**Comment by cdx873v** [comment]
Hi!

Thank's a bunch!

It seems the manufacturer assumed some level of expertise from the
customer. But it's not always that easy to understand something that's
totally new to you. Especially when the only help you can find is if you
know someone. Hopefully your guide will help the next clueless person as
well. Just like it did me!


Best regards

Patrik Engborg

Den sön 29 jan. 2023 17:43Hank™ ***@***.***> skrev:
